---
name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install

    - name: Test
      run: npm run test

    - name: Deploy
      run: |
        git config --global user.name 'juancr5'
        git config --global user.email 'juan.rojas9@udea.edu.co'
        git remote set-url origin https://x-access-token:${{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}}@github.com/${{test-deploy}}    
        npm run deploy